version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"  # Changé de 5000 à 8080
    environment:
      - FLASK_ENV=production
      - PORT=8080  # Changé de 5000 à 8080
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped